# Generated by Django 4.1 on 2024-03-02 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_subject_code_alter_subject_credit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="status",
            new_name="present_status",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="course",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="department",
        ),
        migrations.RemoveField(
            model_name="class",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="class",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="result",
            name="class_related",
        ),
        migrations.RemoveField(
            model_name="student",
            name="course",
        ),
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="class_related",
        ),
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="class",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
