# Generated by Django 4.1 on 2024-03-02 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_result_grade_alter_result_grade_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holiday",
            old_name="start_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="holiday",
            name="end_date",
        ),
    ]
