# Generated by Django 4.1 on 2024-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_timetable_options_result_class_related_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
