# Generated by Django 4.1 on 2024-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_exam_exam_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_id",
            field=models.CharField(max_length=100),
        ),
    ]
