# Generated by Django 4.1 on 2024-03-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_exam_exam_id_alter_result_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
