# Generated by Django 4.1 on 2024-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="description",
        ),
    ]
